/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'announcementType' : AnnouncementType,
  'createdAt' : bigint,
  'isActive' : boolean,
  'companyName' : string,
  'companyId' : Principal,
}
export type AnnouncementType = { 'TradeOffer' : null } |
  { 'NewProduct' : null } |
  { 'Promotion' : null } |
  { 'General' : null };
export interface BuyerStats {
  'totalOrders' : bigint,
  'pendingOrders' : bigint,
  'deliveredOrders' : bigint,
}
export interface CompanyStats {
  'totalProducts' : bigint,
  'totalOrders' : bigint,
  'pendingOrders' : bigint,
  'totalRevenue' : number,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'supplierName' : string,
  'createdAt' : bigint,
  'productId' : bigint,
  'productName' : string,
  'updatedAt' : bigint,
  'totalAmount' : number,
  'notes' : string,
  'buyerId' : Principal,
  'quantity' : bigint,
  'buyerName' : string,
  'unitPrice' : number,
  'buyerRole' : UserRole,
  'supplierId' : Principal,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'Shipped' : null } |
  { 'Pending' : null };
export interface Product {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'minimumOrderQty' : bigint,
  'isActive' : boolean,
  'imageUrl' : string,
  'currency' : string,
  'companyName' : string,
  'category' : string,
  'unitPrice' : number,
  'stockAvailable' : bigint,
  'companyId' : Principal,
}
export interface UserProfile {
  'userId' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'description' : string,
  'address' : string,
  'contactEmail' : string,
  'companyName' : string,
  'phone' : string,
}
export type UserRole = { 'Distributor' : null } |
  { 'Retailer' : null } |
  { 'Company' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'cancelOrder' : ActorMethod<[bigint], undefined>,
  'createAnnouncement' : ActorMethod<
    [string, string, AnnouncementType],
    bigint
  >,
  'createProduct' : ActorMethod<
    [string, string, string, number, bigint, bigint, string],
    bigint
  >,
  'deactivateAnnouncement' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllActiveAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllActiveProducts' : ActorMethod<[], Array<Product>>,
  'getAllCompanyProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAnnouncementsByCompany' : ActorMethod<[Principal], Array<Announcement>>,
  'getAnnouncementsByType' : ActorMethod<
    [AnnouncementType],
    Array<Announcement>
  >,
  'getBuyerStats' : ActorMethod<[], BuyerStats>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCompanyProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getCompanyStats' : ActorMethod<[], CompanyStats>,
  'getIncomingOrders' : ActorMethod<[], Array<Order>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getProductsByCompany' : ActorMethod<[Principal], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[bigint, bigint, string], bigint>,
  'registerUser' : ActorMethod<
    [string, UserRole, string, string, string, string, string],
    UserProfile
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProductsByName' : ActorMethod<[string], Array<Product>>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'updateAnnouncement' : ActorMethod<
    [bigint, string, string, AnnouncementType, boolean],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, string, number, bigint, bigint, string, boolean],
    undefined
  >,
  'updateUserProfile' : ActorMethod<
    [string, string, string, string, string, string],
    UserProfile
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];