/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AnnouncementType = IDL.Variant({
  'TradeOffer' : IDL.Null,
  'NewProduct' : IDL.Null,
  'Promotion' : IDL.Null,
  'General' : IDL.Null,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'announcementType' : AnnouncementType,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'companyName' : IDL.Text,
  'companyId' : IDL.Principal,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'minimumOrderQty' : IDL.Nat,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'currency' : IDL.Text,
  'companyName' : IDL.Text,
  'category' : IDL.Text,
  'unitPrice' : IDL.Float64,
  'stockAvailable' : IDL.Nat,
  'companyId' : IDL.Principal,
});
export const UserRole = IDL.Variant({
  'Distributor' : IDL.Null,
  'Retailer' : IDL.Null,
  'Company' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'description' : IDL.Text,
  'address' : IDL.Text,
  'contactEmail' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const BuyerStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'pendingOrders' : IDL.Nat,
  'deliveredOrders' : IDL.Nat,
});
export const CompanyStats = IDL.Record({
  'totalProducts' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'pendingOrders' : IDL.Nat,
  'totalRevenue' : IDL.Float64,
});
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Shipped' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'supplierName' : IDL.Text,
  'createdAt' : IDL.Int,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'updatedAt' : IDL.Int,
  'totalAmount' : IDL.Float64,
  'notes' : IDL.Text,
  'buyerId' : IDL.Principal,
  'quantity' : IDL.Nat,
  'buyerName' : IDL.Text,
  'unitPrice' : IDL.Float64,
  'buyerRole' : UserRole,
  'supplierId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'cancelOrder' : IDL.Func([IDL.Nat], [], []),
  'createAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, AnnouncementType],
      [IDL.Nat],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deactivateAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllActiveAnnouncements' : IDL.Func(
      [],
      [IDL.Vec(Announcement)],
      ['query'],
    ),
  'getAllActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllCompanyProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAnnouncementsByCompany' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Announcement)],
      ['query'],
    ),
  'getAnnouncementsByType' : IDL.Func(
      [AnnouncementType],
      [IDL.Vec(Announcement)],
      ['query'],
    ),
  'getBuyerStats' : IDL.Func([], [BuyerStats], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCompanyProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getCompanyStats' : IDL.Func([], [CompanyStats], ['query']),
  'getIncomingOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProductsByCompany' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'registerUser' : IDL.Func(
      [IDL.Text, UserRole, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [UserProfile],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProductsByName' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'seedSampleData' : IDL.Func([], [], []),
  'updateAnnouncement' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, AnnouncementType, IDL.Bool],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [UserProfile],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AnnouncementType = IDL.Variant({
    'TradeOffer' : IDL.Null,
    'NewProduct' : IDL.Null,
    'Promotion' : IDL.Null,
    'General' : IDL.Null,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'announcementType' : AnnouncementType,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'companyName' : IDL.Text,
    'companyId' : IDL.Principal,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'minimumOrderQty' : IDL.Nat,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'currency' : IDL.Text,
    'companyName' : IDL.Text,
    'category' : IDL.Text,
    'unitPrice' : IDL.Float64,
    'stockAvailable' : IDL.Nat,
    'companyId' : IDL.Principal,
  });
  const UserRole = IDL.Variant({
    'Distributor' : IDL.Null,
    'Retailer' : IDL.Null,
    'Company' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'description' : IDL.Text,
    'address' : IDL.Text,
    'contactEmail' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const BuyerStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'pendingOrders' : IDL.Nat,
    'deliveredOrders' : IDL.Nat,
  });
  const CompanyStats = IDL.Record({
    'totalProducts' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'pendingOrders' : IDL.Nat,
    'totalRevenue' : IDL.Float64,
  });
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Shipped' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'supplierName' : IDL.Text,
    'createdAt' : IDL.Int,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'updatedAt' : IDL.Int,
    'totalAmount' : IDL.Float64,
    'notes' : IDL.Text,
    'buyerId' : IDL.Principal,
    'quantity' : IDL.Nat,
    'buyerName' : IDL.Text,
    'unitPrice' : IDL.Float64,
    'buyerRole' : UserRole,
    'supplierId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'cancelOrder' : IDL.Func([IDL.Nat], [], []),
    'createAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, AnnouncementType],
        [IDL.Nat],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deactivateAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllActiveAnnouncements' : IDL.Func(
        [],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'getAllActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllCompanyProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAnnouncementsByCompany' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'getAnnouncementsByType' : IDL.Func(
        [AnnouncementType],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'getBuyerStats' : IDL.Func([], [BuyerStats], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCompanyProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getCompanyStats' : IDL.Func([], [CompanyStats], ['query']),
    'getIncomingOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByCompany' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'registerUser' : IDL.Func(
        [IDL.Text, UserRole, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [UserProfile],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProductsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'seedSampleData' : IDL.Func([], [], []),
    'updateAnnouncement' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, AnnouncementType, IDL.Bool],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [UserProfile],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };